main:
    - name: Bio
      url: '#about'
      weight: 10
    - name: Papers
      url: '#publications'
      weight: 20
    - name: Experience
      url: '#experience'
      weight: 30
    - name: Projects
      url: '#projects'
      weight: 40
    - name: Skills
      url: '#skills'
      weight: 50
    - name: Contact
      url: '#contact'
      weight: 60
